### ISSUE TITLE
Error when using browser_domain

### ISSUE THREAD

**Issue by georg90** [MichaelTatarski/fake-http-header#1]
When trying to use
```python
fake_header = FakeHttpHeader(browser_domain = 'de')
print(fake_header)
```

it returns 

`TypeError: __init__() got an unexpected keyword argument 'browser_domain'`

using latest version from PyPi

It should be `domain_name ` then it's working - Typo in code or readme?

Thanks for this awesome work! Really helps :-)

**Comment by MichaelTatarski** [comment]
Thanks for the kind words. It is indeed a typo in the readme file. :-)
