### ISSUE TITLE
missing "eu" entry

### ISSUE THREAD

**Issue by TannhauserGate420** [MichaelTatarski/fake-http-header#2]
I miss the "eu" entry at top-level-domain-to-languages.json

**Comment by MichaelTatarski** [comment]
This is a good catch! There is in fact no "eu" entry.

The languages of the European Union should comprise the languages spoken in the member countries (read this [link ](https://en.wikipedia.org/wiki/Languages_of_the_European_Union#Official_EU_languages)as a reference).

Could you create a PR for this issue?

**Comment by TannhauserGate420** [comment]
sorry - but simply no time. I dont even have time for my own side projects. you should add this asap because of this key error (or add an exception). 

domain:  eu
browser:  edge
return random.choice(DOMAIN_TO_LANGUAGES[domain_name])
KeyError: 'eu'

**Comment by MichaelTatarski** [comment]
Fixed this issue.
